# Generated by Django 3.1 on 2020-08-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=180)),
                ('article', models.TextField(max_length=5000)),
                ('date', models.DateField(auto_now=True)),
                ('viewers', models.PositiveIntegerField()),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
