# Generated by Django 3.1 on 2020-08-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='identifier',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
